version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8888:8888"  # Map port 8888 on the host to port 8888 in the container
    # env_file:
    #   - ./.env
